### ISSUE TITLE
NPE in RunAndWait in 2.5.0

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#255]
Got the following panic which didn't show up in our integration tests:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4c90e7]

goroutine 1 [running]:
panic(0xb50160, 0xc820018080)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/joyent/containerpilot/commands.RunAndWait(0xc820180180, 0xc8201974d0, 0xc820189e20, 0x0, 0x0)
        /cp/src/github.com/joyent/containerpilot/commands/commands.go:97 +0xb87
github.com/joyent/containerpilot/core.(*App).Run(0xc82017c0e0)
        /cp/src/github.com/joyent/containerpilot/core/app.go:147 +0x37e
main.main()
        /cp/src/github.com/joyent/containerpilot/main.go:25 +0xf1
```

The relevant section appears to be [here in `RunAndWait`](https://github.com/joyent/containerpilot/blob/08cbcc600facfcf7b1eb1879ffe8e9f2a5c4cac4/commands/commands.go#L95-L100) where we're incorrectly assuming `state` is never `nil` if we get an non-nil `err` (which seemed reasonable but wasn't documented and turns out to be wrong). We want to capture the state if it's available but otherwise return the error without getting the state. Fix for this should be:

```go
	state, err := c.Cmd.Process.Wait()
	if state != nil && !state.Success()) {
		if status, ok := state.Sys().(syscall.WaitStatus); ok {
			return status.ExitStatus(), err
		}
	}
	if err != nil {
		return 1, err
	}
```

**Comment by tgross** [comment]
I'm adding some test coverage improvements and pruning an unused branch of the error handling in the process here, but should have a PR up later today.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/256
