### ISSUE TITLE
Core dump: Containerpilot version 2.5.0 , Consul 0.7.1

### ISSUE THREAD

**Issue by jacobloveless** [joyent/containerpilot#257]
I'm not familiar with Go and this on is an LX-Branded zone (Ubuntu 14.04 Docker on JPC). Is there a crash dump I can access to help debug this?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4c90e7]

goroutine 48 [running]:
panic(0xb50160, 0xc82000e0a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/joyent/containerpilot/commands.RunAndWait(0xc8200b5680, 0xc8201f7aa0, 0xc820071ef8, 0x0, 0x0)
	/cp/src/github.com/joyent/containerpilot/commands/commands.go:97 +0xb87
github.com/joyent/containerpilot/coprocesses.(*Coprocess).Start(0xc820011860)
	/cp/src/github.com/joyent/containerpilot/coprocesses/coprocess.go:127 +0x2cb
created by github.com/joyent/containerpilot/core.(*App).handleCoprocesses
	/cp/src/github.com/joyent/containerpilot/core/app.go:334 +0x7b
2016/12/07 21:19:46 strconv.ParseFloat: parsing "": invalid syntax
2016/12/07 21:19:46 strconv.ParseFloat: parsing "": invalid syntax
```

**Comment by tgross** [comment]
I believe you can run with `GOTRACEBACK=crash` to get a coredump, which you'd then need to extract via `docker cp` I think. But before you go down that path, this looks like it's hitting the same code path as https://github.com/joyent/containerpilot/issues/255, the fix for which was released in https://github.com/joyent/containerpilot/releases/tag/2.5.1
