### ISSUE TITLE
invalid inputs to -putmetric subcommand can panic

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#364]
While doing https://github.com/joyent/containerpilot/pull/363 I misread the code for the -putmetric subcommand and passed the following invalid subcommand: `/bin/containerpilot -putmetric '{"containerpilot_app_some_counter": 42}'`. This panics [here](https://github.com/joyent/containerpilot/blob/bf56b79d6d4b287072905d15e4549606e934c601/core/flags.go#L27) in `MultiFlag.Set`.  Note that this doesn't panic the running ContainerPilot application, just our subcommand call.

```
time="2017-05-16T15:03:12Z" level=info msg="panic: runtime error: slice bounds out of range"
time="2017-05-16T15:03:12Z" level=info
time="2017-05-16T15:03:12Z" level=info msg="goroutine 1 [running]:"
time="2017-05-16T15:03:12Z" level=info msg="github.com/joyent/containerpilot/core.(*MultiFlag).Set(0xc42000c0c0, 0x7ffd60efce4f, 0x27, 0x0, 0x0)"
time="2017-05-16T15:03:12Z" level=info msg="\t/go/src/github.com/joyent/containerpilot/core/flags.go:27 +0x1c7"
time="2017-05-16T15:03:12Z" level=info msg="flag.(*FlagSet).parseOne(0xc420066060, 0x0, 0x2, 0xc420035d80)"
time="2017-05-16T15:03:12Z" level=info msg="\t/usr/local/go/src/flag/flag.go:894 +0x3c2"
time="2017-05-16T15:03:12Z" level=info msg="flag.(*FlagSet).Parse(0xc420066060, 0xc42000e280, 0x2, 0x2, 0x895047, 0x46)"
time="2017-05-16T15:03:12Z" level=info msg="\t/usr/local/go/src/flag/flag.go:913 +0x60"
time="2017-05-16T15:03:12Z" level=info msg="flag.Parse()"
time="2017-05-16T15:03:12Z" level=info msg="\t/usr/local/go/src/flag/flag.go:941 +0x72"
time="2017-05-16T15:03:12Z" level=info msg="github.com/joyent/containerpilot/core.LoadApp(0x1, 0x4, 0x0)"
time="2017-05-16T15:03:12Z" level=info msg="\t/go/src/github.com/joyent/containerpilot/core/app.go:90 +0xbf8"
time="2017-05-16T15:03:12Z" level=info msg="main.main()"
time="2017-05-16T15:03:12Z" level=info msg="\t/go/src/github.com/joyent/containerpilot/main.go:20 +0x33"
```

Looks like we're checking the length of the array is non-zero but not that it's otherwise valid input.

**Comment by tgross** [comment]
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.3
