### ISSUE TITLE
ContainerPilot configuration cannot be parsed

### ISSUE THREAD

**Issue by lucj** [joyent/containerpilot#444]
- what is happening

I'm currently migrating an application to use ContainerPilot 3.x. I'm getting the following error message while starting a service. This is linked to a syntax error in containerpilot.json5 file but validation seems to be fine though: ```cat containerpilot.json5 | node_modules/json5-validator/json5-validator.js```

```
2017-07-24T13:47:48.006538484Z Received event:db-change
2017-07-24T13:47:48.006565896Z DB-EVENT
2017-07-24T13:47:48.006583538Z onchange-db exited with error: exit status 1
2017-07-24T13:47:51.160667562Z db is healthly, moving on...
2017-07-24T13:47:51.929146049Z
2017-07-24T13:47:51.92917299Z > api@0.0.0 start /app
2017-07-24T13:47:51.929177083Z > node ./bin/www
2017-07-24T13:47:51.929192403Z
2017-07-24T13:47:52.41247311Z /app/containerpilot.json5:3
2017-07-24T13:47:52.412554263Z   jobs: [
2017-07-24T13:47:52.412569962Z       ^
2017-07-24T13:47:52.412579441Z SyntaxError: Unexpected token :
2017-07-24T13:47:52.412641711Z     at Object.exports.runInThisContext (vm.js:76:16)
2017-07-24T13:47:52.412675754Z     at Module._compile (module.js:542:28)
2017-07-24T13:47:52.412708746Z     at Object.Module._extensions..js (module.js:579:10)
2017-07-24T13:47:52.41272354Z     at Module.load (module.js:487:32)
2017-07-24T13:47:52.412731837Z     at tryModuleLoad (module.js:446:12)
2017-07-24T13:47:52.412739823Z     at Function.Module._load (module.js:438:3)
2017-07-24T13:47:52.412748021Z     at Module.require (module.js:497:17)
2017-07-24T13:47:52.412757561Z     at require (internal/module.js:20:19)
2017-07-24T13:47:52.412808943Z     at Object.<anonymous> (/app/app.js:11:24)
2017-07-24T13:47:52.41285316Z     at Module._compile (module.js:570:32)
2017-07-24T13:47:52.421227374Z
````

- the output of `containerpilot -version`

ContainerPilot version 3.3.0 is specified in the Dockerfile.

```
# Install ContainerPilot
ENV CONTAINERPILOT_VER 3.3.0

RUN export CONTAINERPILOT_CHECKSUM=62621712ef6ba755e24805f616096de13e2fd087 \
    && curl -Lso /tmp/containerpilot.tar.gz \
         "https://github.com/joyent/containerpilot/releases/download/${CONTAINERPILOT_VER}/containerpilot-${CONTAINERPILOT_VER}.tar.gz" \
    && echo "${CONTAINERPILOT_CHECKSUM}  /tmp/containerpilot.tar.gz" | sha1sum -c \
    && tar zxf /tmp/containerpilot.tar.gz -C /usr/local/bin \
    && rm /tmp/containerpilot.tar.gz

# COPY ContainerPilot configuration
COPY containerpilot.json5 /etc/containerpilot.json5
ENV CONTAINERPILOT /etc/containerpilot.json5
```

- the ContainerPilot configuration

```
{
  consul: 'localhost:8500',
  logging: {
    level: "DEBUG",
    format: "text"
  },
  jobs: [
    {
      // This one will start first as no "when" field is specified
      name: "preStart",
      exec: "/app/manage.sh prestart"
    },
    {
      name: "api",
      port: 80,
      exec: "npm start",
      when: {
        source: "preStart",
        once: "exitSuccess"
      },
      health: {
        exec: "/usr/bin/curl -o /dev/null --fail -s http://localhost/health",
        interval: 10,
        ttl: 25
      }
    },
    {
      name: 'consul-agent',
      exec: ['/usr/local/bin/consul', 'agent',
                  '-data-dir=/data',
                  '-config-dir=/config',
                  '-log-level=err',
                  '-rejoin',
                  '-retry-join', '{{ .CONSUL | default "consul" }}',
                  '-retry-max', '10',
                  '-retry-interval', '10s'],
      restarts: 'unlimited'
    },
    {
      name: 'onchange-db',
      exec: '/app/manage.sh db-change',
      when: {
        source: 'watch.mongodb-replicaset',
        each: 'changed'
      }
    }
  ],
  watches: [
    {
      name: 'mongodb-replicaset',
      interval: 2
    }
  ]
}
```

I cannot figure out what I'm missing.

**Comment by geek** [comment]
@lucj That will parse fine with json5. What version of piloted are you running or what does your parsing code look like?

**Comment by lucj** [comment]
@geek package.json has piloted version "3.x.x".

The part that does the parsing:

```
const express        = require('express'),
      ...
      Piloted        = require('piloted'),
      ContainerPilot = require('./containerpilot.json5');

// Manage connection to the underlying database (connection + reload)
Piloted.config(ContainerPilot, (err) => {
    winston.info("ContainerPilot configuration:" + (err ? err.message : "ok"));

    // Connect to the underlying database
    db.connect(function(err) {
        if(err){
            winston.error("DB connection:" + err.message);
            process.exit(1);
        }
    });

    // Reconnect when ContainerPilot reloads its configuration
    Piloted.on('refresh', () => {
        winston.warn("DB reconnection triggered...");
        db.reconnect(function(err) {
            if(err) {
                winston.error(util.format("DB reconnection failed: %s", err.message));
            }
        });
    });
});
```

**Comment by geek** [comment]
@lucj the `require('./containerpilot.json5');` is where this is failing. With version 3 of piloted you no longer need to load the configuration file, as it will be done for you using the `CONTAINERPILOT` environment variable. I'll update the piloted documentation to make this clear.

https://github.com/joyent/node-piloted/blob/master/test/index.js#L39

**Comment by lucj** [comment]
@geek thanks, I have no more error when changing the parsing to the following (removing the call to 'config').  Is that the way to go with 3.x ?

```
...
db             = require('./lib/db'),
Piloted        = require('piloted');

// Connect to the underlying database
db.connect(function(err) {
    if(err){
        winston.error("DB connection:" + err.message);
        process.exit(1);
    }
});

// Reconnect when ContainerPilot reloads its configuration
Piloted.on('refresh', () => {
    winston.warn("DB reconnection triggered...");
    db.reconnect(function(err) {
        if(err) {
            winston.error(util.format("DB reconnection failed: %s", err.message));
        }
    });
});
```

**Comment by geek** [comment]
@lucj yep, looks great to me! Going to close this for now. Feel free to reopen if you have any more issues.

**Comment by tgross** [comment]
Just dropping a link here for history to the module under discussion: https://github.com/joyent/node-piloted
